name: gitutil-migrate-repository
run-name: Migrate by @${{ github.actor }}
on:
  push:
    branches:
      - '**.sh'

jobs:
  gitutil-run:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "Running script ..."
          ls -lthr