name: GITUTIL CD
on:
  push:
    branches:
      - main

jobs:
  python-ci:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "TEST WORKFLOWS"
          ls -lthr